### ISSUE TITLE
Misspelled word "supress" in command line options

### ISSUE THREAD

**Issue by mortenfyhn** [AvyFly/parasect#125]
Hi! I saw your post on the PX4 Spotlight page and started looking into your project.

I noticed in the command line reference that the options `--supress-calibration` and `--supress-operator-defined` seem to be misspelled (should be "suppress").

**Comment by Georacer** [comment]
You are not wrong! I'll fix it on the next patch.
Thanks for reporting!

**Comment by mortenfyhn** [comment]
Lovely, thank _you_!
