### ISSUE TITLE
Wrong example used in documentation

### ISSUE THREAD

**Issue by TitusBraber** [AvyFly/parasect#80]
In the latest version of the documentation, on the concepts page: https://parasect.readthedocs.io/en/latest/concepts.html

The first example has the following description:

> The Meal is made up of Dishes. Each Dish represents a notional subset of the autopilot’s parameters, which makes it easier to define and manage. In this case light_meal contains the Dishes dish_1, dish_2, header and footer.

However, the example file which is located above it, seems to be the wrong example, or the description itself is wrong:

> Example meals.yaml file:

Also see screenshot:
![image](https://user-images.githubusercontent.com/2298791/176463075-186aa133-854a-48a6-b979-24cd2482ca8b.png)

**Comment by Georacer** [comment]
Thanks for reporting! It should be fixed now, you can take another look if you want! Enjoy your meal!

**Comment by TitusBraber** [comment]
Hi @Georacer,

I see the example file has been updated, to contain

> light_meal:
  frame_id: 1
  salad: ~
  meat_and_potatoes: ~
  remove_calibration: True
  remove_operator: True
  header: ~
  footer: ~

But the description still says

> In this case light_meal contains the Dishes dish_1, dish_2, header and footer.

I think `dish_1` and `dish_2` should probably be renamed to `salad` and `meat_and_potatoes`. 


In addition, I believe the `remove_calibration` and `remove_operator` is confusing in this example, but that's unrelated.

**Comment by Georacer** [comment]
Ah, my bad. I'll take another look. Thanks for reporting.

**Comment by Georacer** [comment]
I think it should be ok now. I also added a TODO example of a Dish file.
